### ISSUE TITLE
Fungible Token Standard

### ISSUE THREAD

**Issue by garwalsh** [o1-labs/rfcs#44]
Will build on: https://forums.minaprotocol.com/t/draft-fungible-token-standard-zkapps/6142

In light of the work to generalise the base token here:
https://app.zenhub.com/workspaces/sdk-6130fedb3b0fc600123d8796/issues/gh/o1-labs/o1js/1274

**Comment by mitschabaude** [comment]
PR that implements and describes new `TokenContract` API: https://github.com/o1-labs/o1js/pull/1384

IMO the `Approvable` and `Transferable` APIs, proposed for the token standard [here](https://forums.minaprotocol.com/t/draft-fungible-token-standard-zkapps/6142) should be changes to exactly match the new `TokenContract` API

Here I proposed that we remove the Callback API, which is done by now: https://github.com/o1-labs/o1js/pull/1402
So the token standard should also no longer rely on that API, but on what the TokenContract does: accepting an `AccountUpdateForest` which contains all the account updates that it has to approve, in one structure

I don't have strong opinions on some of the "viewable" APIs in the standard

I don't thing the `Pausable` API proposed there is needed.

**Comment by Trivo25** [comment]
see https://app.zenhub.com/workspaces/sdk-6130fedb3b0fc600123d8796/issues/zh/102
